/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package property;

import java.awt.Font;

/**
 *
 * @author DELL
 */
public class TextPanel extends javax.swing.JPanel {
private static final int PLAIN=Font.PLAIN;  //kiểu chữ thường
    private static final int BOLD=Font.BOLD;    //kiểu chữ in đậm
    private static final int ITALIC=Font.ITALIC;//kiểu chữ in nghiêng
    
    private String fontName;//tên Font chữ
    private int fontStyle;//kiểu Font chữ
    private int fontSize;//Kích thước chữ
    
    private boolean isOpaque; // >< transparent:trong suốt. liên quan đến vấn đề đoạn văn bản sau và đoạn văn bản trước có phần giao nhau
    private Font font; 
//getter and setter 
     public boolean isIsOpaque() {
        return isOpaque;
    }

    public void setIsOpaque(boolean isOpaque) {
        this.isOpaque = isOpaque;
    }
    public String getFontName() {
        return fontName;
    }

    public void setFontName(String fontName) {
        this.fontName = fontName;
    }

    public int getFontStyle() {
        return fontStyle;
    }

    public void setFontStyle(int fontStyle) {
        this.fontStyle = fontStyle;
    }

    public int getFontSize() {
        return fontSize;
    }

    public void setFontSize(int fontSize) {
        this.fontSize = fontSize;
    }
    
@Override
    public Font getFont() {
        return font;
    }
    public void setFont(String fontName,int fontStyle,int fontSize) {
        this.font = new Font(fontName,fontStyle,fontSize);
    }
    
    /**
     * Creates new form TextPanel
     */
    public TextPanel() {
        initComponents();
        //khởi tao mặc định 
        this.setFontName("Agency FB");
        this.setFontSize(11);
        this.setFontStyle(PLAIN);
        this.setFont(fontName,fontStyle,fontSize);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
